### ISSUE TITLE
Allow style element

### ISSUE THREAD

**Issue by kikz4life** [Kaishiyoku/laravel-html-purifier#1]
Is it possible to allow <style>body{color:red)</style>?

**Comment by Kaishiyoku** [comment]
I will try to add that rule today.

**Comment by Kaishiyoku** [comment]
Ok I evaluated this and I'm wondering why you need the style tag. I can allow the style attribute for certain tags like a \<div/> for example. `<div style="color: red;">text</div>`

Your request tells me that you purify your whole HTML? In most cases it would be sufficient to only purify user input because your "static" templates are clear and under your control.

**Comment by Div-Man** [comment]
Hello, how to disable the width property for the style element?

**Comment by Div-Man** [comment]
Hello, how to disable the width property for the style element?

**Comment by Kaishiyoku** [comment]
@Div-Man I'm uncertain if you can control which style attributes to allow and which not. I doubt that it will be easily possible.

**Comment by Kaishiyoku** [comment]
Due to no more response I will close this issue. If there is still any need of white-flagging the style attribute please let me know.
